### ISSUE TITLE
Backstage Import Issue

### ISSUE THREAD

**Issue by chussenot** [incident-io/catalog-importer#141]
Hi @lawrencejones I've got some issue with the backstage configuration? Can you help to understand the param to pass the CLI and the needed secret? Below you backstage configuration and the Makefile I wrote to wrap the CLI calls.

Cheers,

![image](https://github.com/user-attachments/assets/ede2acc8-9da5-426a-a290-03f87e1c6727)

```Makefile
# Makefile
# Environment variables for API keys and tokens
BACKSTAGE_TOKEN ?= $(shell echo $$BACKSTAGE_TOKEN)
INCIDENT_API_KEY ?= $(shell echo $$INCIDENT_API_KEY)
BACKSTAGE_SIGN_JWT=false
DOMAIN ?= $(shell echo $$DOMAIN)

# Backstage endpoint
BACKSTAGE_ENDPOINT ?= "https://$(DOMAIN)/api/catalog/entities"

# Incident.io API endpoint
INCIDENT_ENDPOINT ?= "https://api.incident.io"

install:
	@go install github.com/incident-io/singer-tap/cmd/tap-incident@latest
  
install-importer: 
	@go install -v github.com/incident-io/catalog-importer/v2/cmd/catalog-importer@latest
	
discover:
	@tap-incident --discover --config=config.json | jq '.' > catalog.json

# Target to import catalog entries into Incident.io from Backstage
import-catalog:
	@if [ -z "$(BACKSTAGE_TOKEN)" ]; then \
		echo "Error: BACKSTAGE_TOKEN environment variable is not set."; \
		exit 1; \
	fi
	@if [ -z "$(INCIDENT_API_KEY)" ]; then \
		echo "Error: INCIDENT_API_KEY environment variable is not set."; \
		exit 1; \
	fi
	catalog-importer backstage \
		--api-key $(INCIDENT_API_KEY) \
		--backstage-token $(BACKSTAGE_TOKEN) \
		--backstage-endpoint $(BACKSTAGE_ENDPOINT) \
		--api-endpoint $(INCIDENT_ENDPOINT) \
		--debug

debug:
	@curl -X GET "https://$(DOMAIN)/api/catalog/entities?filter=kind=component,spec.type=service&fields=metadata.name,metadata.uid,metadata.etag,metadata.tags,spec.owner" \
	-H "Content-Type: application/json" -H "Authorization: Bearer ${BACKSTAGE_TOKEN}" | jq .

# Optional help target
help:
	@echo "Usage:"
	@echo "  make import-catalog - Imports catalog entries from Backstage to Incident.io"
	@echo "Environment Variables:"
	@echo "  BACKSTAGE_TOKEN   - $(BACKSTAGE_TOKEN)"
	@echo "  INCIDENT_API_KEY  - $(INCIDENT_API_KEY)"
```

```yaml
# app-config.yaml (Backstage)
backend:                                                                                          
  # Used for enabling authentication, secret is shared by all backend plugins                     
  # See https://backstage.io/docs/auth/service-to-service-auth for                                
  # information on the format                                                                     
  auth:                                                                                           
    # Used for enabling the backstage API                                                         
    # https://backstage.io/docs/auth/service-to-service-auth/#usage-in-external-callers           
    externalAccess:                                                                               
      - type: legacy                                                                              
        options:                                                                                  
          secret: app-secret                                                                      
          subject: legacy-token                                                                   
      - type: static                                                                              
        options:                                                                                  
          token: xxxx                                                                             
          subject: token                                                                          
    # dangerouslyDisableDefaultAuthPolicy: true                                                   
```
