### ISSUE TITLE
Support deploying.md with docker image exec source dependencies and examples

### ISSUE THREAD

**Issue by swanson8r** [incident-io/catalog-importer#178]
As an SRE attempting to follow the [Deploying using CI > Github Actions ](https://github.com/incident-io/catalog-importer/blob/f062b546c6e1258232ce2d51c378f2f390b1cbf1/docs/deploying.md#github-actions) instructions, I encountered a number of frustrations (some of them self-inflicted in the absence of clear guidance.)

1. When attempting to configure an [exec source](https://github.com/incident-io/catalog-importer/blob/f062b546c6e1258232ce2d51c378f2f390b1cbf1/docs/sources.md#exec), the [docker image](https://hub.docker.com/r/incidentio/catalog-importer) returns with errors:
  - `catalog-importer: error: loading entries from source: exec`  ... `error running exec command: fork/exec`
    - This can be resolved by adding `--entrypoint /bin/sh`
    - (tested with `actions/checkout@v4` and `docker run`) 
2. Only the [Gitlab CI](https://github.com/incident-io/catalog-importer/tree/f062b546c6e1258232ce2d51c378f2f390b1cbf1/docs#gitlab-ci) example includes a `before_script:` step to `# Install curl and other dependencies` with `apt-get update && apt-get install -y curl`
  - The docker image is Alpine Linux, which returns `/bin/sh: apt-get: not found`
    - The fix: `apk update; apk add curl jq` 
    - (Thanks to local testing against the `docker export` file)

While it would be delightful to have required binaries such as `jq` and `curl` included in the docker image to be able to follow the most basic exec source options, at a minimum these should be provided as consistent examples for each Deploying method, or else cautioned against with a valid reason.

**Comment by louisheath** [comment]
Apologies for the frustration here @swanson8r and thank you for the detailed feedback 🙏

I will add this context to a ticket aimed at reviewing and revising the instructions on this page

Were you able to reach a working configuration?

**Comment by swanson8r** [comment]
Not yet, but having identified these issues should help us press forward.

A few additional findings since I posted the issue (and am happy to update in the description if you'd like them captured in one place as a checklist for a PR):

3. https://app.incident.io/~/catalog/manage-in-github is a convenient way for most users to begin engaging with catalog-importer, since it creates the configs for an existing UI-managed type. There is no mention of this UI feature in the [docs](https://github.com/search?q=repo%3Aincident-io%2Fcatalog-importer+%22github%22+language%3AMarkdown&type=code&l=Markdown), nor are there any link to the [product help docs](https://github.com/search?q=repo%3Aincident-io%2Fcatalog-importer+%22help.incident%22+language%3AMarkdown&type=code).  The closest I could find is some tangential mention in an issue: https://github.com/incident-io/catalog-importer/issues/141
  - I recommend dedicating a section of an existing readme to a walk-through of this feature; This may be best served by updating and linking to [Catalog Best Practices > Managing Catalog Types in GitHub](https://help.incident.io/articles/2752354608-managing-catalog-types-in-github)
4. The choice to use Jsonnet makes sense to me due to the complexity of the schema attributes needing to be configure, but feels overwhelming who are not familiar with its syntax.
- Consider linking to  [Config > File Format](https://github.com/incident-io/catalog-importer/blob/master/docs/config.md#file-format) from the main README to better address this emotional barrier to entry.
-  Providing examples (screenshot, short animated gif, or link to an existing [youtube](https://www.youtube.com/@incident-io/) or Loom demo) of _how_ the VSCode extension makes this process easier,  readme.
- I see Yaml is also mentioned as an option; An example there would also help with this barrier.

**Comment by swanson8r** [comment]
`cat import-catalog-dry-run.yml | pbcopy`
```yaml
name: incident-catalog-importer-dry-run
run-name: 🔥 (DRY RUN) Importing catalog to incident.io
on:
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch: # allow manual trigger
env:
  API_KEY: "${{ secrets.INCIDENT_API_KEY }}"
  PULL_REQUEST_TITLE: "${{ github.event.pull_request.title }}"
jobs:
  import-incident-io-catalog-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Dry-run incident.io catalog importer
        run: |
          echo "🔥 Catalog importer dry run for changes made in Pull Request- ${{ env.PULL_REQUEST_TITLE }}"
          docker run \
            -v $(pwd):/config --workdir /config \
            -e 'INCIDENT_API_KEY=${{ env.API_KEY }}' \
            -e 'INCIDENT_ENDPOINT=https://api.incident.io' \
            -e "SOURCE_REPO_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            --rm \
            incidentio/catalog-importer:v2 \
            sync --config importer.jsonnet --dry-run
```

`cat import-catalog.yml | pbcopy`
```yaml
name: incident-catalog-importer
run-name: 🔥 Importing catalog to incident.io
on:
  push:
    branches: ["main", "master"]
  workflow_dispatch: # allow manual trigger
env:
  API_KEY: "${{ secrets.INCIDENT_API_KEY }}"
jobs:
  import-incident-io-catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run incident.io catalog importer
        run: |
          echo "🔥 Importing catalog to incident.io"
          docker run \
            -v $(pwd):/config --workdir /config \
            -e 'INCIDENT_API_KEY=${{ env.API_KEY }}' \
            -e 'INCIDENT_ENDPOINT=https://api.incident.io' \
            -e "SOURCE_REPO_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            --rm \
            incidentio/catalog-importer:v2 \
            sync --config importer.jsonnet

```
